on: [push]

jobs:
  soos_csa_analysis:
    name: SOOS CSA Scan
    runs-on: ubuntu-latest
    steps:
    - name: Run SOOS CSA
      uses: soos-io/soos-csa-github-action@c1c5845125fcf51101d616778e44e5af67ffeca2
      with:
        image_tag: 'beta'
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        api_url: "https://qa-api.soos.io/api/"
        project_name: "csa_gha_test"
        target_image: "ericallard/elasticsearch:x86"
        log_level: "DEBUG"
        #export_format: "sarif"
        export_file_type: "json"
    - uses: actions/upload-artifact@v4
      with:
        name: 'reports'
        path: '*'
    - name: Upload SOOS DAST SARIF Report
      uses: github/codeql-action/upload-sarif@v3
